site_name: "PRO1-kompendium"
site_url: https://sva-via.github.io/PRO1-kompendium/
site_description: "Kompendium til PRO1"

theme:
  name: material
  language: da
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      toc_depth: 2
      permalink: true

plugins:
  - search

nav:
  - Forside: index.md
  - Kapitler:
      - "Kapitel 1: Hvad er et objekt?": kapitel/01.md
